# Codemagic configuration for Contacts Dashboard App
workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      groups:
        - google_play
      vars:
        EXPO_USERNAME: $EXPO_USERNAME
        EXPO_PASSWORD: $EXPO_PASSWORD
        EXPO_PROJECT_ID: $EXPO_PROJECT_ID
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set up EAS
        script: |
          npm install -g eas-cli@latest
          echo "$EXPO_PASSWORD" | eas login --username "$EXPO_USERNAME"
      - name: Build Android APK
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - "*.apk"
      - "*.aab"
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-build-unsigned:
    name: Android Build (Unsigned)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      vars:
        EXPO_USERNAME: $EXPO_USERNAME
        EXPO_PASSWORD: $EXPO_PASSWORD
        EXPO_PROJECT_ID: $EXPO_PROJECT_ID
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set up EAS
        script: |
          npm install -g eas-cli@latest
          echo "$EXPO_PASSWORD" | eas login --username "$EXPO_USERNAME"
      - name: Build Android APK (Unsigned)
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - "*.apk"
      - "*.aab"
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  ios-build:
    name: iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 18.17.0
      npm: 9.6.7
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        EXPO_USERNAME: $EXPO_USERNAME
        EXPO_PASSWORD: $EXPO_PASSWORD
        EXPO_PROJECT_ID: $EXPO_PROJECT_ID
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set up EAS
        script: |
          npm install -g eas-cli@latest
          echo "$EXPO_PASSWORD" | eas login --username "$EXPO_USERNAME"
      - name: Build iOS
        script: |
          eas build --platform ios --profile preview --non-interactive
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  expo-build:
    name: Expo Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      vars:
        EXPO_USERNAME: $EXPO_USERNAME
        EXPO_PASSWORD: $EXPO_PASSWORD
        EXPO_PROJECT_ID: $EXPO_PROJECT_ID
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set up EAS
        script: |
          npm install -g eas-cli@latest
          echo "$EXPO_PASSWORD" | eas login --username "$EXPO_USERNAME"
      - name: Update EAS configuration
        script: |
          eas update --auto
      - name: Build for Expo
        script: |
          eas build --platform all --profile production --non-interactive
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
