# Codemagic configuration for Contacts Dashboard App
workflows:
  android-build:
    name: Android Build (Debug)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install expo-build-properties --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Clean and prebuild Android project
        script: |
          rm -rf android ios
          npx expo prebuild --platform android
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: List build outputs
        script: |
          find android/app/build/outputs -name "*.apk" -type f
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-build-release:
    name: Android Build (Release Unsigned)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install expo-build-properties --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Clean and prebuild Android project
        script: |
          rm -rf android ios
          npx expo prebuild --platform android
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build Android Release APK (Unsigned)
        script: |
          cd android
          ./gradlew assembleRelease
      - name: List build outputs
        script: |
          find android/app/build/outputs -name "*.apk" -type f
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
