# Codemagic configuration for Contacts Dashboard App
workflows:
  android-build:
    name: Android Build (Debug)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install expo@^53.0.0 react-native@^0.79.0 --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Create missing assets
        script: |
          mkdir -p assets
          # Create a simple 1024x1024 PNG icon using ImageMagick (available on mac_mini_m1)
          convert -size 1024x1024 xc:blue assets/icon.png
          convert -size 1024x1024 xc:green assets/adaptive-icon.png
          convert -size 1284x2778 xc:white assets/splash.png
          convert -size 32x32 xc:blue assets/favicon.png
      - name: Clean and prebuild Android project
        script: |
          rm -rf android ios
          npx expo prebuild --platform android --no-install
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: List build outputs
        script: |
          find android/app/build/outputs -name "*.apk" -type f
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-build-release:
    name: Android Build (Release Unsigned)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install expo@^53.0.0 react-native@^0.79.0 --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Create missing assets
        script: |
          mkdir -p assets
          # Create simple placeholder images
          convert -size 1024x1024 xc:blue assets/icon.png
          convert -size 1024x1024 xc:green assets/adaptive-icon.png
          convert -size 1284x2778 xc:white assets/splash.png
          convert -size 32x32 xc:blue assets/favicon.png
      - name: Clean and prebuild Android project
        script: |
          rm -rf android ios
          npx expo prebuild --platform android --no-install
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build Android Release APK (Unsigned)
        script: |
          cd android
          ./gradlew assembleRelease
      - name: List build outputs
        script: |
          find android/app/build/outputs -name "*.apk" -type f
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
